sudo: false
language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1

matrix:
    include:
        - php: 5.5
          env: PHPUNIT_VERSION="^4.8.36"
        - php: 7.2
          env: PHPUNIT_VERSION="^7.0"
        - php: 7.3
          env: PHPUNIT_VERSION="^7.0"

install:
    - composer update --no-interaction
    - if [ "$PHPUNIT_VERSION" != "" ]; then composer require phpunit/phpunit:"$PHPUNIT_VERSION" --no-interaction; fi;

before_script:
    - mkdir -p build/logs

script:
    - if [ "$PHPUNIT_VERSION" = "" ]; then phpunit --coverage-clover build/logs/clover.xml; fi
    - if [ "$PHPUNIT_VERSION" != "" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi

after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar -t 3; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;
